#ifndef _BUFFER_SIZES_
#define _BUFFER_SIZES_

#define BUFFER_SIZE_PATH (1024)
#define BUFFER_SIZE_HOSTNAME (128)
#define BUFFER_SIZE_USERNAME (128)
#define BUFFER_SIZE_INPUT (1024)
#define BUFFER_SIZE_ARGUMENTS (64)
#define BUFFER_SIZE_PROCESS_COUNT (1024)

#endif